import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Footer from '../components/Footer'
import '../translation/i18n';
import { useTranslation } from 'react-i18next';
import Typical from 'react-typical'
import Experiences from "../components/Experiences";
import Skills from "../components/Skills";

export default function Home() {
  const { t, i18n } = useTranslation();

  return (
    <div>
      <Head>
        <title>Clément LEFIEF - Développeur Web et Mobile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section className="w-4/5 mx-auto">
          {/* Hero */}
          <div className="flex flex-col items-center mx-auto">
              <h1 className="text-5xl mt-10 text-center font-bold py-5">{t("hero.h1")}</h1>
              <p className="text-center text-xl font-light pb-5">{t("hero.p")}</p>
              <Image 
                src="/assets/img/me.jpg"
                alt="Me at university"
                width={250}
                height={250}
                className="rounded-full"
              />
          </div>
        </section>
        {/* About */}
        <section className="mt-20" style={{backgroundColor: "#fedd00"}}>
            <div className="w-4/5 mx-auto py-10 md:w-3/5">
              <h2 className="text-4xl text-center text-black font-semibold">{t("about.h2")}</h2>
              <p className="text-md text-center text-black py-5">{t("about.p")}</p>
            </div>
        </section>
          {/* Skills */}
          <Skills />
          {/* Exp */}
          <Experiences />
          {/* Footer */}
        <Footer />
      </main>

    </div>
  )
}
